"use client"

import { IconToolTip } from "@/components/icon-tooltip"
import InfoTooltip from "@/components/info-tooltip"
import { TooltipInfo } from "@/svgs"

export default function Metrics() {
  return (
    <div className="grid grid-cols-5">
      <div className="flex items-end space-x-3 px-5">
        <div className="bg-muted p-2 w-10 rounded-xl text-cloud-100 flex justify-center">
          ix
        </div>
        <div className="flex flex-col space-y-2">
          <span className="flex items-center">
            <span className="opacity-70 text-sm">Strategies PnL</span>
            <InfoTooltip className="pb-0.5">
              Profit or loss of your strategies.
            </InfoTooltip>
          </span>
          <span className="font-medium text-2xl">-$1.23</span>
        </div>
      </div>
      <div className="flex items-end space-x-3 px-5">
        <div className="bg-muted p-2 w-10 rounded-xl text-cloud-100 flex justify-center">
          ix
        </div>
        <div className="flex flex-col space-y-2">
          <span className="flex items-center">
            <span className="opacity-70 text-sm">Avg.strategies return</span>
            <InfoTooltip className="pb-0.5">
              Average return of your strategies over 30 days.
            </InfoTooltip>
          </span>
          <span className="font-medium text-2xl">13%</span>
        </div>
      </div>
      <div className="flex items-end space-x-3 px-5">
        <div className="bg-muted p-2 w-10 rounded-xl text-cloud-100 flex justify-center">
          ix
        </div>
        <div className="flex flex-col space-y-2">
          <span className="flex items-center">
            <span className="opacity-70 text-sm">Total points</span>
            <InfoTooltip className="pb-0.5">
              Points accumulated by trading, providing liquidity, and referrals.
            </InfoTooltip>
          </span>
          <span className="font-medium text-2xl">3223</span>
        </div>
      </div>
      <div className="flex items-end space-x-3 px-5">
        <div className="bg-muted p-2 w-10 rounded-xl text-cloud-100 flex justify-center">
          ix
        </div>
        <div className="flex flex-col space-y-2">
          <span className="flex items-center">
            <span className="opacity-70 text-sm">Volume generated</span>
            <InfoTooltip className="pb-0.5">
              Total volume generated by your provided liquidity.
            </InfoTooltip>
          </span>
          <span className="font-medium text-2xl">$263.64</span>
        </div>
      </div>
      <div className="flex items-end space-x-3 px-5">
        <div className="bg-muted p-2 w-10 rounded-xl text-cloud-100 flex justify-center">
          ix
        </div>
        <div className="flex flex-col space-y-2">
          <span className="flex items-center">
            <span className="opacity-70 text-sm">Volume traded</span>
            <InfoTooltip className="pb-0.5">
              Total volume generated by your direct trading activity.
            </InfoTooltip>
          </span>
          <span className="font-medium text-2xl">$63.64</span>
        </div>
      </div>
    </div>
  )
}
